### ISSUE TITLE
Add Workshop filtering and groups 

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#16]
Once we start creating content, and possibly making the tool accessible to others, it might make sense to categorize workshops and possibly modules, and provide filtering.

Example:
https://kiosk-dot-codelabs-site.appspot.com/devoxx?cat=Compute

![image](https://cloud.githubusercontent.com/assets/78350/23763631/bb030522-04fa-11e7-86f2-7bcbbedf60ca.png)

**Comment by marekjelen** [comment]
There you are pretty much trying to recreate Katacode, is it where we want to go?

//cc @thoraxe @siamaksade @gshipley @GrahamDumpleton @thesteve0

**Comment by thesteve0** [comment]
I like the left navigation between the different steps that Jorge showed. In general I like katacoda and then the google site even more and I think it would work for your environment

**Comment by siamaksade** [comment]
+1 for the left navigation
