### ISSUE TITLE
Add file a bug link 

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#17]
Possibly for the tool and for the content, so we can get direct issues from the workshops.

Example:
![image](https://cloud.githubusercontent.com/assets/78350/23763718/fec60052-04fa-11e7-96af-4c2b20b41ef3.png)

**Comment by marekjelen** [comment]
can you propose updates to _config.yml structure to track this information?

**Comment by marekjelen** [comment]
@jorgemoralespou is this still valid request?

**Comment by jorgemoralespou** [comment]
This should point to the repository from where the content comes from.

Potentially we could add to _config.yml

```
name: "<NAME>"
id: "<ID>"
report-broken: true|false (or yes|no)
[report-broken-url: <REPO_URL>]
vars:
   <LIST>
modules:
   <LIST>
```

If (report-broken == true) and there is report-broken-url then use this one, else, use CONTENT_URL_PREFIX

**Comment by marekjelen** [comment]
Add 
```
config:
  issues: URL
```

to `_modules.yml`
