### ISSUE TITLE
Add syntax colouring to the renderer

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#18]
As we're using asciidoc, it should be possible to display code with rendering colours.

Example:
![image](https://cloud.githubusercontent.com/assets/78350/23763790/5404eff6-04fb-11e7-98e7-7f90b4f06825.png)

**Comment by marekjelen** [comment]
The kiosk uses https://github.com/google/code-prettify/

Asciidoctor has support for highlightjs, 13d1b730aaee6de341773d1005975423596bef93 enables syntax highlighting on Asciidoctor, adds highlightjs to the project, but does not enable syntax highlighting. But the content needs to be fixed before enabling syntax highlighting, as we e.g. use source code block for quoted blocks and that makes mess.

Documentation: http://asciidoctor.org/docs/user-manual/#source-code-blocks

**Comment by marekjelen** [comment]
Fixed in the ruby branch, will be available once merged.
