### ISSUE TITLE
Splash page for showing large URL link to workshop content.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-evangelists/workshopper#26]
When running workshop in a room with real people and have workshop notes on projection screen, would be nice for workshopper app to have a way of showing the URL, in very large text in a splash screen. This way as soon as people come in they can see the URL and go to notes straight away. Don't need to create a document in something else where can make URL really large and visible. Bonus points if allow you to supply a short paragraph to show with it, also in large text, so can say what URL is for and that they should go to it straight away. Right now options are to include in workshop name or use a '##' title to show it.

![image](https://cloud.githubusercontent.com/assets/507637/25832084/b9020166-34ab-11e7-9b02-b447413d6798.png)

**Comment by marekjelen** [comment]
Do you still want this?

I have been using bit.ly (bit.ly/conferenceworkshop) that I show the attendees and has link to all relevant places.

**Comment by GrahamDumpleton** [comment]
In most cases have a separate slide deck which presenting first and so can display the link there. It was only cases where doing a workshop at conference with little time and had no slide deck which was problem. People were coming late and needed to show it somehow. The workarounds I give are fine to a degree, might still be useful, but you can leave it as low priority.

**Comment by marekjelen** [comment]
@thoraxe @siamaksade @jorgemoralespou @gshipley any opinions?

**Comment by thoraxe** [comment]
For the Ops workshop each student gets their own workshopper so this isn't relevant to "me".

**Comment by jorgemoralespou** [comment]
It's not critical, but if it's easy to solve, is nice to have. I often go from the slides to workshop per and people ask me to show the url again frequently.

**Comment by GrahamDumpleton** [comment]
Closing this since managing without it.
