### ISSUE TITLE
All in one page title

### ISSUE THREAD

**Issue by marekjelen** [openshift-evangelists/workshopper#30]
https://github.com/openshift-evangelists/workshop-summit/issues/5

**Comment by marekjelen** [comment]
Workshop names are not changed in `_modules.yml` because they are supposed to be reused between workshops. Workshop definition files allow change the name for that particular workshop.

**Comment by thesteve0** [comment]
Where is that file? I don't think it should be in the docker image as that requires a recompile of the image for each workshop
