### ISSUE TITLE
Conditional statements does not work correctly in serverside branch

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/workshopper#31]
Serverside branch does not evaluate conditional statements for active modules correctly:
```
{% if modules.demos_msa-cicd-eap %}
ACTIVATED
{% else %}
NOT ACTIVATED
{% endif %}
```
Using `latest`, the above statements prints `ACTIVATED` for a specific workshop while using the `serverside`, it would always evaluate to `NOT ACTIVATED`.

**Comment by marekjelen** [comment]
Interesting, I will look into that ... after a quick review, the information should be there, might be that the translation between the Java based web application and the JRuby based rendering does not interpret the values correctly.

**Comment by marekjelen** [comment]
Closing as the serverside will be deprecated anyway.
