### ISSUE TITLE
Create s2i image

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#32]
So that I can just pass all the content statically, if hosted on a single repository, and have it in the image to avoid going to the internet for every page.

**Comment by jorgemoralespou** [comment]
Still relevant. I can probably do this one.

**Comment by marekjelen** [comment]
Still relevant?

**Comment by jorgemoralespou** [comment]
yeah.
Or else, a template :-D

But you know I like that once you build the deployment, all the files are local to the deployment and not dependant on internet

**Comment by jorgemoralespou** [comment]
template is there: https://github.com/openshift-labs/starter-guides/blob/master/guides-template.yaml

Not 100% ok for any workshopper but close :-D

**Comment by marekjelen** [comment]
ok, I will try to build the S2I part and will keep the template to you, @jorgemoralespou

**Comment by marekjelen** [comment]
@jorgemoralespou added in 0164f7f

By default it will use `_workshop.yml` in the root of the repo. In case you want to use some other worksop from that repo you can override using `WORKSHOP_PATH=workshops/myworkshop.yml` or you can use use `WORKSHOPS_URLS` with full path(s) as you do today.
