### ISSUE TITLE
Breadcrumb of current module always visible

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#38]
Add the current module as a breadcrumb on the top panel, so that you always know what lab you're in.

![screen shot 2017-08-30 at 18 28 28](https://user-images.githubusercontent.com/78350/29883723-721815a6-8db1-11e7-9402-17818bd6b277.png)

Of course, with nice styles.

**Comment by marekjelen** [comment]
Done and in modern browsers the TOC on the left will stay in place.
