### ISSUE TITLE
Invalid links in table of content

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/workshopper#40]
When generating a ToC using markdown `{:toc}` syntax, the generates links are the `http://host/index.html#myheader` which interferes with the angular routing.

**Comment by marekjelen** [comment]
correct ... single page app vs. html anchors 

not sure yet how to get around that :(

**Comment by marekjelen** [comment]
in the updated version anchors will not be used for navigation anymore, thus should not clash with the TOC
