### ISSUE TITLE
make exercise area wider or configurable

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/workshopper#42]
The narrow width of the area for exercises really makes certain things difficult -- especially displaying long shell commands or wide command output.

* can we make the exercise area wider?
* can we make the width of the exercise area configurable?

**Comment by thoraxe** [comment]
If we made it possible to load additional CSS files this could be pretty easy.

**Comment by marekjelen** [comment]
The area is now wider in the `ruby` branch and flexes based on the windows size.
