### ISSUE TITLE
admonition text and list definition text is bigger than normal paragraph text 

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/workshopper#44]
When using admonitions (eg: `NOTE:`) or definition lists (eg: `<2>`), the resulting text on the page has a larger size than normal paragraph text.

I'm seeing a computed text size for admonitions and DLs as 16px, whereas regular paragraph text is 14px.

I'd think this should all be the same?

**Comment by thesteve0** [comment]
Admonitions should definitely be larger as they are intended to catch the
users eye. They are larger, bold, and usually have an icon when rendered in
asciidoctor or in the O'Reilly atlas system. I am not sure with list items

Coming at you from my phone, please excuse typos, poor grammar, curtness,
and dashing good looks

**Comment by marekjelen** [comment]
Cleaned up the CSS in new version, will release ASAP for testing.
