### ISSUE TITLE
Add scroll to "table of contents"

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#48]
In order to look into following modules, I need to scroll current to the end, so that table of contents also scrolls.

![image](https://user-images.githubusercontent.com/78350/37023680-f8780fb2-2126-11e8-9a9c-30cd98c58d31.png)

The database lab is a good example as it's long. Also, when you select it, the table of contents showing current lab can be out of the "viewport".

![image](https://user-images.githubusercontent.com/78350/37023752-2a6fb100-2127-11e8-8cee-5da998f5125d.png)

**Comment by marekjelen** [comment]
Updated, the menu is statically placed at the top.

**Comment by jorgemoralespou** [comment]
@marekjelen Looks good, but this is what I was thinking: https://kiosk-dot-codelabs-site.appspot.com/codelabs/firebase-monetization-tips/index.html?index=..%2F..%2Findex#0

**Comment by marekjelen** [comment]
What is the benefit? The link has client side rendering, which we do not. We reload the whole page. 

Make your browser window small in height. When I am on the last item visible and click next, then the selected item does not get scrolled into the view and is hidden. It's possible to have 100% height scrollable area a and have some logic to always keep the current item in view, but not sure it's worth the effort.

Or let me ask differently, what do you want to achieve?

**Comment by jorgemoralespou** [comment]
As the title of the issue says: "Add scroll to table of contents" and when I say Scroll, I meant scrollbar.

**Comment by marekjelen** [comment]
Closing as it's too much work with no real benefit.

If there is some easy solution or somebody wants to contribute, I will be happy to accept.
