### ISSUE TITLE
Add different indicator of copy and paste

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#50]
Red box around the text for copy and paste functionalities might not be enough, as it's not really clear what it does.

Maybe add an icon, like learn.openshift.com has that makes it more clear.

![image](https://user-images.githubusercontent.com/78350/37023907-b7704bb4-2127-11e8-8be8-3afdfd2793dd.png)

In this case, I would add it to the left top corner and not right top corner.

**Comment by marekjelen** [comment]
Implemented by @siamaksade ... thanks!
