### ISSUE TITLE
Make issues configurable per workshop

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#51]
The new feature to report issues (https://github.com/marekjelen/starter-guides/blob/master/_modules.yml#L2) should be configruable per workshop so that I can deliver a workshop with my own content/fork, with changes that are not yet merged in master and that I don't need to edit this link and commit.

I want to be able to fix issues reported to my own fork before merging the content back. This is helpful when you want to run dry a workshop.

**Comment by marekjelen** [comment]
Fixed in e93a626.

Override using `ISSUES_URL` env variable.
